version: "2"
services:
    db:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_USER: dedi
            MYSQL_PASSWORD: dedi
            MYSQL_ROOT_PASSWORD: dedi
        volumes:
            - ./db:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - 8002:80
        environment:
            MYSQL_USER: dedi
            MYSQL_PASSWORD: dedi
            MYSQL_ROOT_PASSWORD: dedi
